CREATE TABLE Usuarios(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Perfil VARCHAR(50) NOT NULL,
	Login VARCHAR(100) NOT NULL,
	Senha VARCHAR(100) NOT NULL
)

CREATE TABLE Receitas (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Descricao VARCHAR(510) NOT NULL,
	Ingredientes VARCHAR(510) NOT NULL,
	ModoDePreparo VARCHAR(510) NOT NULL,
	TempoDePreparo INT NOT NULL,
	NumeroDePorcoes INT NOT NULL,
	LinkImagem VARCHAR(510) NOT NULL,
	LinkVideo VARCHAR(510)
)